steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'login',
      '--username=${_DOCKERHUB_USERNAME}',
      '--password=${_DOCKERHUB_PAT}'
    ]
    secretEnv: ['_DOCKERHUB_PAT']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'docker.io/${_DOCKERHUB_USERNAME}/${_DOCKERHUB_REPO_NAME}:${COMMIT_SHA}',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'docker.io/${_DOCKERHUB_USERNAME}/${_DOCKERHUB_REPO_NAME}:${COMMIT_SHA}'
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '${_CLOUD_RUN_SERVICE_NAME}',
      '--image=docker.io/${_DOCKERHUB_USERNAME}/${_DOCKERHUB_REPO_NAME}:${COMMIT_SHA}',
      '--region=${_REGION}',
      '--platform=managed',
      '--allow-unauthenticated',
      '--port=8080',
      '--set-env-vars=NEXT_PUBLIC_SANITY_PROJECT_ID=${_SANITY_PROJECT_ID},NEXT_PUBLIC_SANITY_DATASET=${_SANITY_DATASET}',
      '--update-secrets=SANITY_API_TOKEN=${_SANITY_API_TOKEN_SECRET_NAME}'
    ]

images:
  - 'docker.io/${_DOCKERHUB_USERNAME}/${_DOCKERHUB_REPO_NAME}:${COMMIT_SHA}'

secrets:
  - secretEnv:
      _DOCKERHUB_PAT: _DOCKERHUB_PAT
      SANITY_API_TOKEN: SANITY_API_TOKEN

substitutions:
  _CLOUD_RUN_SERVICE_NAME: travelogue
  _DOCKERHUB_REPO_NAME: travelogue
  _DOCKERHUB_USERNAME: samuelajayii
  _REGION: europe-west1
  _SANITY_PROJECT_ID: inojoc9p
  _SANITY_DATASET: production
  _SANITY_API_TOKEN_SECRET_NAME: SANITY_API_TOKEN
